# -*- coding: utf-8 -*-
"""LESSON 3 - PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3-y_tcIt9wy-OVyqXRj4aSiG_FAtBWU
"""

n = int(input('Please enter the number: '))

if n > 0 :
  print('Đây là số nguyên dương')
elif n < 0:
  print('Đây là số nguyên âm')
else:
  print('Đây là số....')

while True:
  n = float(input('Mời nhập điểm: '))

  if n < 0 or n > 10:
    print('Mời nhập lại, số điểm không hợp lệ!')
  elif n >= 8:
    print('Xếp lại giỏi')
  elif n >= 4 and n < 6.5:
    print('Xếp loại trung bình')
  elif n >= 6.5 and n < 8:
    print('Xếp lại khá')
  elif n < 4:
    print('Xếp loại yếu')
  else:
    print('Khó nói')
  option = input('\nBạn muốn nhập tiếp điểm học sinh nào không?:(y/n)')
  if option != 'y':
    print('Bye bye, have a good day!')
    break
    print('-' * 30)

import math

a = float(input('Mời nhập hệ số a: '))
b = float(input('Mời nhập hệ số b: '))
c = float(input('Mời nhập hệ số c: '))

if a == 0:
  if b == 0:
    if c == 0:
      print('Phương trình vô số nghiệm')
    else:
      print('Phương trình vô nghiệm')
  else:
    x = -c/b
    print(f'Phương trình bậc nhất có nghiệm: x = {x:.2f}')
else:
  delta = b**2 - 4*a*c
  if delta < 0:
    print('Phương trình vô nghiệm')
  elif delta == 0:
    x = -b/ (2 * a)
    print(f"Phương trình có nghiệm kép: x1 = x2 = {x:.2f}")
  else:
    x1 = (-b + math.sqrt(delta)) / (2 * a)
    x2 = (-b - math.sqrt(delta)) / (2 * a)
    print(f"Phương trình có 2 nghiệm phân biệt:")
    print(f"x1 = {x1:.2f}")
    print(f"x2 = {x2:.2f}")

# "Ba mươi sáu con": Tổng số gà và chó là 36
# "Một trăm chân chẵn": Tổng số chân là 100.
# Biết rằng: Mỗi con gà có 2 chân, mỗi con chó có 4 chân.

tong_con = 36
tong_so_chan = 100

cho = (tong_so_chan - tong_con * 2) // (4-2)
ga = tong_con - cho

print(f"Số con gà là: {ga} con")
print(f"Số con chó là: {cho} con")

day = int(input('Mời nhập ngày: '))
month = int(input('Mời nhập tháng: '))
Year = int(input('Mời nhập năm: '))

password = "123"
count = 0
max_attempt = 3

while count < max_attempt:
 pass_w = input('Mời nhập mật khẩu: ')

 if pass_w == password:
   print('Chào mừng bro/sis tới trang')
   break
 else:
  count += 1
  count_down = max_attempt - count
  if count_down > 0:
    print(f'Bro còn lại {count_down} thôi đó nha, ráng nhớ đi bro/sis')
  else:
    print('Lưu ý nha bro/sis chỉ có 3 lần nhập thôi đấy')

